
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import Header from "./header";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Murdoch Badminton Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/image.ico" />
      </head>

      <body className={inter.className}>
      <div className="flex flex-col min-h-screen">
        <Header />
        {children}
        <Footer />
      </div>
        </body>
    </html>
  );
}





